name: API Automation Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test:
    name: Run API Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up JDK 14
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '14'

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Run API Tests
        run: mvn clean test

      - name: Upload JUnit Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: JUnit Reports
          path: target/surefire-reports/

      - name: Upload Extent Report
        uses: actions/upload-artifact@v4
        with:
          name: Extent Reports
          path: target/extent-reports/extent-report.html
